import { Header } from "@/components/Header/Header";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora, Nunito } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const LoraFont = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const NunitoFont = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${LoraFont.variable} ${NunitoFont.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
